<template>
  <section class="py-12">
    <div class="container mx-auto max-w-[1000px]">
      <h1 class="text-3xl font-semibold mb-9">
        Política de privacidad
      </h1>
      <div class="flex flex-col gap-4">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque placerat tristique scelerisque. Duis viverra, nisl et pulvinar mattis, elit ipsum rutrum nisi, in congue quam mauris eget ante. Ut augue nisi, cursus ut magna eu, dapibus mollis nulla. Nunc nulla nisi, posuere at eros ut, pharetra imperdiet elit. Aliquam dignissim arcu vitae nulla varius, at dignissim elit venenatis. Pellentesque ornare ipsum non pharetra posuere. Pellentesque et faucibus mi. Etiam viverra magna et sapien feugiat sodales. Nulla facilisi. Cras facilisis dui sit amet dapibus faucibus. Curabitur at mi a lectus elementum tincidunt. Vivamus tempor diam non mauris fringilla scelerisque. Integer fermentum facilisis tortor vitae egestas. Phasellus placerat lorem sed eros bibendum gravida in sed est. Curabitur velit nibh, gravida quis orci quis, finibus fringilla sapien.
          Suspendisse turpis sem, vulputate eu sapien ut, hendrerit ullamcorper enim. Duis dolor eros, pellentesque a ex tristique, vulputate posuere nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris eu magna eu nisi suscipit maximus. In hac habitasse platea dictumst. Nulla facilisi. Cras gravida lacus eget auctor volutpat. Curabitur eu pharetra sapien. Suspendisse lacinia lacinia elit id sollicitudin. Vestibulum sed elementum velit, ut tincidunt velit. Sed vestibulum erat neque, id facilisis mi suscipit ac. Maecenas porttitor urna ut ultricies bibendum.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque placerat tristique scelerisque. Duis viverra, nisl et pulvinar mattis, elit ipsum rutrum nisi, in congue quam mauris eget ante. Ut augue nisi, cursus ut magna eu, dapibus mollis nulla. Nunc nulla nisi, posuere at eros ut, pharetra imperdiet elit. Aliquam dignissim arcu vitae nulla varius, at dignissim elit venenatis. Pellentesque ornare ipsum non pharetra posuere. Pellentesque et faucibus mi. Etiam viverra magna et sapien feugiat sodales. Nulla facilisi. Cras facilisis dui sit amet dapibus faucibus. Curabitur at mi a lectus elementum tincidunt. Vivamus tempor diam non mauris fringilla scelerisque. Integer fermentum facilisis tortor vitae egestas. Phasellus placerat lorem sed eros bibendum gravida in sed est. Curabitur velit nibh, gravida quis orci quis, finibus fringilla sapien.
          Suspendisse turpis sem, vulputate eu sapien ut, hendrerit ullamcorper enim. Duis dolor eros, pellentesque a ex tristique, vulputate posuere nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris eu magna eu nisi suscipit maximus. In hac habitasse platea dictumst. Nulla facilisi. Cras gravida lacus eget auctor volutpat. Curabitur eu pharetra sapien. Suspendisse lacinia lacinia elit id sollicitudin. Vestibulum sed elementum velit, ut tincidunt velit. Sed vestibulum erat neque, id facilisis mi suscipit ac. Maecenas porttitor urna ut ultricies bibendum.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque placerat tristique scelerisque. Duis viverra, nisl et pulvinar mattis, elit ipsum rutrum nisi, in congue quam mauris eget ante. Ut augue nisi, cursus ut magna eu, dapibus mollis nulla. Nunc nulla nisi, posuere at eros ut, pharetra imperdiet elit. Aliquam dignissim arcu vitae nulla varius, at dignissim elit venenatis. Pellentesque ornare ipsum non pharetra posuere. Pellentesque et faucibus mi. Etiam viverra magna et sapien feugiat sodales. Nulla facilisi. Cras facilisis dui sit amet dapibus faucibus. Curabitur at mi a lectus elementum tincidunt. Vivamus tempor diam non mauris fringilla scelerisque. Integer fermentum facilisis tortor vitae egestas. Phasellus placerat lorem sed eros bibendum gravida in sed est. Curabitur velit nibh, gravida quis orci quis, finibus fringilla sapien.
          Suspendisse turpis sem, vulputate eu sapien ut, hendrerit ullamcorper enim. Duis dolor eros, pellentesque a ex tristique, vulputate posuere nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris eu magna eu nisi suscipit maximus. In hac habitasse platea dictumst. Nulla facilisi. Cras gravida lacus eget auctor volutpat. Curabitur eu pharetra sapien. Suspendisse lacinia lacinia elit id sollicitudin. Vestibulum sed elementum velit, ut tincidunt velit. Sed vestibulum erat neque, id facilisis mi suscipit ac. Maecenas porttitor urna ut ultricies bibendum.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque placerat tristique scelerisque. Duis viverra, nisl et pulvinar mattis, elit ipsum rutrum nisi, in congue quam mauris eget ante. Ut augue nisi, cursus ut magna eu, dapibus mollis nulla. Nunc nulla nisi, posuere at eros ut, pharetra imperdiet elit. Aliquam dignissim arcu vitae nulla varius, at dignissim elit venenatis. Pellentesque ornare ipsum non pharetra posuere. Pellentesque et faucibus mi. Etiam viverra magna et sapien feugiat sodales. Nulla facilisi. Cras facilisis dui sit amet dapibus faucibus. Curabitur at mi a lectus elementum tincidunt. Vivamus tempor diam non mauris fringilla scelerisque. Integer fermentum facilisis tortor vitae egestas. Phasellus placerat lorem sed eros bibendum gravida in sed est. Curabitur velit nibh, gravida quis orci quis, finibus fringilla sapien.
          Suspendisse turpis sem, vulputate eu sapien ut, hendrerit ullamcorper enim. Duis dolor eros, pellentesque a ex tristique, vulputate posuere nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris eu magna eu nisi suscipit maximus. In hac habitasse platea dictumst. Nulla facilisi. Cras gravida lacus eget auctor volutpat. Curabitur eu pharetra sapien. Suspendisse lacinia lacinia elit id sollicitudin. Vestibulum sed elementum velit, ut tincidunt velit. Sed vestibulum erat neque, id facilisis mi suscipit ac. Maecenas porttitor urna ut ultricies bibendum.
        </p>
      </div>
    </div>
  </section>
</template>
